jQuery(document).ready(function(){
    var scripts = document.getElementsByTagName("script");
    var jsFolder = "";
    for (var i= 0; i< scripts.length; i++)
    {
        if( scripts[i].src && scripts[i].src.match(/initcarousel-1\.js/i))
            jsFolder = scripts[i].src.substr(0, scripts[i].src.lastIndexOf("/") + 1);
    }
    if ( typeof html5Lightbox === "undefined" )
    {
        html5Lightbox = jQuery(".html5lightbox").html5lightbox({
            skinsfoldername:"",
            jsfolder:jsFolder,
            barheight:64,
            showtitle:true,
            showdescription:false,
            shownavigation:false,
            thumbwidth:80,
            thumbheight:60,
            thumbtopmargin:12,
            thumbbottommargin:8,
            titlebottomcss:'{color:#333; font-size:14px; font-family:Armata,sans-serif,Arial; overflow:hidden; text-align:left;}',
            descriptionbottomcss:'{color:#333; font-size:12px; font-family:Arial,Helvetica,sans-serif; overflow:hidden; text-align:left; margin:4px 0px 0px; padding: 0px;}'
        });
    }
    jQuery("#amazingcarousel-1").amazingcarousel({
        jsfolder:jsFolder,
        width:350,
        height:240,
        skinsfoldername:"",
        itembottomshadowimagetop:99,
        random:false,
        rownumber:1,
        skin:"TestimonialCarousel",
        responsive:true,
        itembottomshadowimage:"itembottomshadow-100-98-3.png",
        watermarklinkcss:"",
        showhoveroverlayalways:false,
        lightboxdescriptionbottomcss:"{color:#333; font-size:12px; font-family:Arial,Helvetica,sans-serif; overflow:hidden; text-align:left; margin:4px 0px 0px; padding: 0px;}",
        supportiframe:false,
        lightboxthumbwidth:80,
        imagefillcolor:"FFFFFF",
        showwatermark:true,
        arrowwidth:32,
        transparent:false,
        continuousduration:2500,
        watermarkpositioncss:"",
        lightboxthumbheight:60,
        navspacing:4,
        playvideoimage:"playvideo-64-64-0.png",
        usescreenquery:false,
        screenquery:{
	tablet: {
		screenwidth: 900,
		visibleitems: 2
	},
	mobile: {
		screenwidth: 600,
		visibleitems: 1
	}
},
        navwidth:16,
        navheight:16,
        watermarkimage:"",
        watermarkstyle:"text",
        imageheight:120,
        lightboxthumbbottommargin:8,
        lightboxtitlebottomcss:"{color:#333; font-size:14px; font-family:Armata,sans-serif,Arial; overflow:hidden; text-align:left;}",
        enabletouchswipe:true,
        navstyle:"bullets",
        arrowstyle:"mouseover",
        navswitchonmouseover:false,
        showitembackgroundimage:false,
        watermarklink:"",
        arrowimage:"arrows-32-32-2.png",
        showbackgroundimage:false,
        spacing:4,
        scrollitems:1,
        navdirection:"horizontal",
        watermarktarget:"",
        bottomshadowimagewidth:110,
        donotcrop:false,
        showhoveroverlay:false,
        height:240,
        itembackgroundimagewidth:100,
        backgroundimagetop:-40,
        width:350,
        hoveroverlayimage:"hoveroverlay-64-64-9.png",
        hidehoveroverlayontouch:false,
        transitioneasing:"easeOutExpo",
        lightboxshownavigation:false,
        itembackgroundimage:"",
        direction:"horizontal",
        watermarktext:"",
        lightboxbarheight:64,
        continuous:false,
        pauseonmouseover:false,
        navimage:"bullet-16-16-1.png",
        lightboxthumbtopmargin:12,
        arrowhideonmouseleave:600,
        backgroundimagewidth:110,
        loop:0,
        arrowheight:32,
        bottomshadowimage:"bottomshadow-110-95-0.png",
        lightboxshowdescription:false,
        bottomshadowimagetop:95,
        showitembottomshadow:false,
        playvideoimagepos:"center",
        circular:true,
        showbottomshadow:false,
        showplayvideo:true,
        itembackgroundimagetop:0,
        lightboxshowtitle:true,
        scrollmode:"page",
        backgroundimage:"",
        lightboxnogroup:false,
        navmode:"page",
        interval:3000,
        watermarktextcss:"",
        itembottomshadowimagewidth:100,
        visibleitems:3,
        imagewidth:120,
        transitionduration:1000,
        autoplay:true
    });
});